import Foundation

struct SuggestedSource: Codable, Identifiable {
	var id: UUID
	var name: String
	/// Validated RSS/Atom feed URL returned by FeedDiscoveryService.
	var feedURL: String
	/// The website homepage URL that was passed to Ollama.
	var websiteURL: String
	/// One-sentence description generated by Ollama.
	var summary: String
	var category: String
	var suggestedAt: Date
	/// Set by the ViewModel based on whether feedURL is already in the user's sources.
	var isAlreadyAdded: Bool = false
}
